services:
  redis:
    image: redis:7-alpine
    container_name: ticketsbot-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    container_name: ticketsbot-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass BASE_DOMAIN for client-side URL derivation
        - NEXT_PUBLIC_BASE_DOMAIN=${BASE_DOMAIN:-localhost}
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - API_HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - RUNNING_IN_DOCKER=true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      # Development volumes
      - .:/app:cached
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
      - /app/apps/bot/node_modules
      - /app/packages/core/node_modules
      - /app/packages/scripts/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      redis:
        condition: service_healthy
