packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@orangeopensource/hurl"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - bufferutil
  - core-js
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
