services:
  - type: web
    name: ticketsbot-api-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    repo: https://github.com/maydotinc/ticketsbot-ai.git
    branch: main
    region: oregon
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
    dockerCommand: pnpm start:production

    buildFilter:
      paths:
        - apps/api/**
        - apps/bot/**
        - packages/core/**
        - packages/scripts/**

        - package.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
        - turbo.json
        - Dockerfile
        - render.yaml
        - .nvmrc

      ignoredPaths:
        - apps/web/**

        - "**/*.md"
        - docs/**

        - "**/*.test.ts"
        - "**/*.spec.ts"
        - "**/tests/**"
        - "**/__tests__/**"

        - .github/**
        - packages/eslint-config/**
        - packages/tsconfig/**
        - packages/vitest-config/**
        - .vscode/**
        - "**/.eslintrc*"

    envVars:
      - fromGroup: ticketsbot-env
      - key: NODE_ENV
        value: production
      - key: TURBO_TELEMETRY_DISABLED
        value: "1"
      - key: TURBO_CACHE_DIR
        value: .turbo
      - key: TURBO_LOG_ORDER
        value: stream

envVarGroups:
  - name: ticketsbot-env
    envVars:
      - key: DATABASE_URL
        value: ""
      - key: BETTER_AUTH_SECRET
        value: ""
      - key: DISCORD_TOKEN
        value: ""
      - key: DISCORD_CLIENT_ID
        value: ""
      - key: DISCORD_CLIENT_SECRET
        value: ""
      - key: WEB_URL
        value: ""
      - key: API_URL
        value: ""
      - key: ALLOWED_ORIGINS
        value: ""
      - key: REDIS_URL
        value: ""
